### ISSUE TITLE
Database import Error

### ISSUE THREAD

**Issue by Sebbl0508** [condolent/esx_repairkit#4]
When importing into MySQL database via phpMyAdmin the error "#1054 - Unknown column 'limit' in 'field list'" comes up

**Comment by b889965** [comment]
> When importing into MySQL database via phpMyAdmin the error "#1054 - Unknown column 'limit' in 'field list'" comes up

'limit' is now 'weight', so rename it in the database file and import it and you should be fine

**Comment by jonteohr** [comment]
fixed
